version: '3.6'
services:
  db:
    restart: unless-stopped
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ../volumes/db:/var/lib/postgresql/data

  graphql:
    restart: unless-stopped
    env_file:
      - ./graphql/.env
    depends_on:
      - db
    build:
      context: graphql
    volumes:
      - ./graphql:/project
    ports:
      - 5000:8080

  hasura_cli_console:
    restart: unless-stopped
    depends_on:
      - graphql
    build:
      context: graphql
      dockerfile: cli.Dockerfile
    volumes:
      - ./graphql:/project
    ports:
      - 9695:9695
    command: > 
      hasura console 
      --log-level DEBUG 
      --address "hasura_cli_console" 
      --no-browser 
      --api-host https://9693-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST} 
      --api-port 443
      --endpoint https://5000-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}
    working_dir: /project

  hasura_cli_api:
    restart: unless-stopped
    depends_on:
      - graphql
    build:
      context: graphql
      dockerfile: cli.Dockerfile
    volumes:
      - ./graphql:/project
    ports:
      - 9693:9693
    command:  hasura console --log-level DEBUG --address "hasura_cli_api" --no-browser 
    working_dir: /project
